# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftCli < Formula
  desc "CLI for interacting with Craft.do documents"
  homepage "https://github.com/sapihav/craft-cli"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.1/craft-cli_Darwin_x86_64.tar.gz"
      sha256 "338094e3a7470493004aca71494a33179497aaa8c4f59ce7002db9671ba67149"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.1/craft-cli_Darwin_arm64.tar.gz"
      sha256 "acbadacaf142aee04a057a24df363c99125ea02163458aa448162e1db2e7bb0a"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.1/craft-cli_Linux_x86_64.tar.gz"
      sha256 "fb7bc127e3fcb1d5a892a568442a801fb68af538eb407313662b55ddc03def5d"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.1/craft-cli_Linux_arm64.tar.gz"
      sha256 "03f5f58304a36e8e7cfb9ed78232403851c0df6c157726df4712bf4955b7b763"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
