# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftCli < Formula
  desc "CLI for interacting with Craft.do documents"
  homepage "https://github.com/sapihav/craft-cli"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.0/craft-cli_Darwin_x86_64.tar.gz"
      sha256 "7142e58f4dbabd9c31c0702be26ee73bf631222238eda06b0ae5a386ea7c48fb"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.0/craft-cli_Darwin_arm64.tar.gz"
      sha256 "15ef8e2a9d2d8a3ba388ff1fc5ea10f6f66b93e0c4997356038d93bb76c44d98"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.0/craft-cli_Linux_x86_64.tar.gz"
      sha256 "60f67b164ce90dceb7fb922281b51629173ab7938e07ef978db530b1ac141bc4"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.10.0/craft-cli_Linux_arm64.tar.gz"
      sha256 "cc4d037d16de3fd0a9d7f636bf9ef9ab0de1b11adc91a8a0fdf0d242f8f1e8a9"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
