# This file was generated by GoReleaser. DO NOT EDIT.
cask "clef" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Darwin_x86_64.tar.gz"
      sha256 "08d98d51f6f61a7eed54c4b9abe9fa97e26d8e29ef635d53258c454450a45ab3"
    end
    on_arm do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Darwin_arm64.tar.gz"
      sha256 "5513371ad63d8fd5633581e8836a438564821e71ee42a9af46dfadf015b1c09e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Linux_x86_64.tar.gz"
      sha256 "a35f8fe66e1903711af731fca1802b5a7b83ca1c1507452caeb4e7cabdbb9d41"
    end
    on_arm do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Linux_arm64.tar.gz"
      sha256 "ae4b6af1279cefc28f459ea647914a82b191fdc2b06c45cdb895ae7b0764a2e8"
    end
  end

  name "clef"
  desc "Per-project Claude Code model and effort configuration"
  homepage "https://github.com/sapihav/clef-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clef"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clef"]
    end
  end

  # No zap stanza required

end
