# This file was generated by GoReleaser. DO NOT EDIT.
cask "clef" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Darwin_x86_64.tar.gz"
      sha256 "dd51602084e99c1a79ee29b69baa208378885cd8dc0cd9cdda05f453d7690477"
    end
    on_arm do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Darwin_arm64.tar.gz"
      sha256 "72b66c831431752243af42bb3b7dfd59784c5a14a8553b04973e2ef405e538de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Linux_x86_64.tar.gz"
      sha256 "8ff78fe1c01a61c565a29cfab2ca4f050105eed2e9db72b33a371fe5c2725e2d"
    end
    on_arm do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Linux_arm64.tar.gz"
      sha256 "ba75343a2277027044645b3d0af8b30cd3a4dfa2a38bb9b804ddf21b0077b167"
    end
  end

  name "clef"
  desc "Per-project Claude Code model and effort configuration"
  homepage "https://github.com/sapihav/clef-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clef"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clef"]
    end
  end

  # No zap stanza required

end
