# This file was generated by GoReleaser. DO NOT EDIT.
cask "clef" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Darwin_x86_64.tar.gz"
      sha256 "1e4881e5528c5d8bafeabd27adf62375e3d01550307b30bd6437685de13a3509"
    end
    on_arm do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Darwin_arm64.tar.gz"
      sha256 "e9c5f6aff44945a9e66b05617c11e82f426d12bb1717c903d6863dd1c5fd127b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Linux_x86_64.tar.gz"
      sha256 "03296cb57cb0204b9ec591ecfd0ea2d29604557746d62b5d0ce6c7975cbe7d16"
    end
    on_arm do
      url "https://github.com/sapihav/clef-cli/releases/download/v#{version}/clef_Linux_arm64.tar.gz"
      sha256 "f8dfdddbf9de29f269cd0f051667f8841d19f5b41f4a270bc25d6c12c9ead841"
    end
  end

  name "clef"
  desc "Per-project Claude Code model and effort configuration"
  homepage "https://github.com/sapihav/clef-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clef"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clef"]
    end
  end

  # No zap stanza required

end
