# This file was generated by GoReleaser. DO NOT EDIT.
cask "exa" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Darwin_x86_64.tar.gz"
      sha256 "37601520dd6c9fff2b47d6593ac189a60b95f64cfa02643b6383a3f143a28b31"
    end
    on_arm do
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Darwin_arm64.tar.gz"
      sha256 "45d3b537f7f476b9cd4b9d6abaa0d56e89b56b4e73becf0e3bd99cbe1ff883da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Linux_x86_64.tar.gz"
      sha256 "4fca455c0c2a20489e09b6f7c41d04a1004d12ec28c8753f4d84a55560ebe895"
    end
    on_arm do
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Linux_arm64.tar.gz"
      sha256 "b892206fb551539d6405a89f10dd421ba6772c2bfac5ba67c685cbd6ffb718fc"
    end
  end

  name "exa"
  desc "Thin CLI for the Exa AI search API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/exa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/exa"]
    end
  end

  # No zap stanza required

end
