# This file was generated by GoReleaser. DO NOT EDIT.
cask "exa" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "f3d7ac3060e6f32d6182a1fdf82c009b78633d8767ded500b317e29c00b3926c"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bccf6f08e11f74c41ef2c1e67839767d682f704248ba48c477fe8933a46f31b8"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b82c42537875bc1f1d52eaddf47da39c69c53025331b1c6812278b0de127606"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "288dd46d61f3a4b0da0ad597f01f1a5439e7b990e61e1a9fb47fb54824ae907b"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Linux_arm64.tar.gz"
    end
  end

  name "exa"
  desc "Thin CLI for the Exa AI search API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/exa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/exa"]
    end
  end

  # No zap stanza required

end
