# This file was generated by GoReleaser. DO NOT EDIT.
cask "exa" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "cec301c6b6920bc75a388c890a4384a6b9c121f5fcb7888f4f3bcc5fa3140c33"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5f1b3ead1ca727471609e2e1febfccbcd814cd6a4a1be779f97081a02f7f5c8a"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "990fb72629aa177c870a70d4bda431ffb93182aad74710c7c14fe4918511bd0e"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3e0a692f76ee6ab198a744db61167ecf8659f0e4f49ca0fdaec495402aad0b4c"
      url "https://github.com/sapihav/exa-cli/releases/download/v#{version}/exa-cli_Linux_arm64.tar.gz"
    end
  end

  name "exa"
  desc "Thin CLI for the Exa AI search API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/exa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "exa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/exa"]
    end
  end

  # No zap stanza required

end
