# This file was generated by GoReleaser. DO NOT EDIT.
cask "perplexity" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "349286b0df251afc60f15e0ed026902d873fa7837125b08ceac80ca81e812a83"
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2e3f8a49cc6f7130c00a9b941e2c6d76c100a0782d936e3120b3d7545dc454dd"
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a302e5dd80294bfb5e8058fe710b442045e5cf79b13edfd6d35e1f4c88cf8059"
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "49eefc47ffb5320073d843a7995615ed9f1ebbe79a6f4b4f1fc7c6572127dfd9"
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Linux_arm64.tar.gz"
    end
  end

  name "perplexity"
  desc "Thin CLI for the Perplexity API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/perplexity-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "perplexity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/perplexity"]
    end
  end

  # No zap stanza required

end
