# This file was generated by GoReleaser. DO NOT EDIT.
cask "perplexity" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Darwin_x86_64.tar.gz"
      sha256 "b3a2eb625e06deba042da6e9224be4f2dfffee1a1f1615d0c7348834fc8e3d06"
    end
    on_arm do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Darwin_arm64.tar.gz"
      sha256 "2d40555ebe3f780cccdf194ecea9d69b48e56ea081563401a7c59645ff37ad6a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Linux_x86_64.tar.gz"
      sha256 "bf993fedd3146b1f38dab1d97c6824e2e19694eb9d1faa853820f9c8224850f5"
    end
    on_arm do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Linux_arm64.tar.gz"
      sha256 "9066cdee490be242b31df088c79fd45f2d601a5eeb0116a184b3f3f44596b878"
    end
  end

  name "perplexity"
  desc "Thin CLI for the Perplexity API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/perplexity-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "perplexity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/perplexity"]
    end
  end

  # No zap stanza required

end
