# This file was generated by GoReleaser. DO NOT EDIT.
cask "perplexity" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Darwin_x86_64.tar.gz"
      sha256 "39409ff001764d908ff265e3454d846645fcc7cc552962456a666fc941872e06"
    end
    on_arm do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Darwin_arm64.tar.gz"
      sha256 "de9fcf923c0c4b0146296a38b33a2eefcfbe4945f66fcf96d346c8f9a33d1b54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Linux_x86_64.tar.gz"
      sha256 "2abc8e13580113b13c9d92c14e2395dfa0d9613031c87bd9f8e08b65ba0d6642"
    end
    on_arm do
      url "https://github.com/sapihav/perplexity-cli/releases/download/v#{version}/perplexity-cli_Linux_arm64.tar.gz"
      sha256 "6a46a07ac10d4163dabef7fbe78461f7cbac4911e98a6267bd7e979063196b4a"
    end
  end

  name "perplexity"
  desc "Thin CLI for the Perplexity API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/perplexity-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "perplexity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/perplexity"]
    end
  end

  # No zap stanza required

end
