# This file was generated by GoReleaser. DO NOT EDIT.
cask "tavily" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "78b1588583ffff485689b7cf63ee330434bc561e624ba745d4355bcb4bafb967"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "69e50cfbb1300e15d5681c9759800026ffef18b6d703ae5c265f4eaf5b6546c6"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd683e2ae0ad094a00b081f56adf9a6b52795454491d046b0ab9b1fedfdadd39"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2086783d9ad33a7f6f9df44c4dfc90884e7695b0690e93ff8f71d1d62603dbca"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Linux_arm64.tar.gz"
    end
  end

  name "tavily"
  desc "Thin CLI for the Tavily search API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/tavily-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tavily"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tavily"]
    end
  end

  # No zap stanza required

end
