# This file was generated by GoReleaser. DO NOT EDIT.
cask "tavily" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "05bed3275c85d598d25670b9e0c4037a3c21db1d5604c531775f0c7569040eb3"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "57e7879d22f8045986c534d4bcb7a6dcb6956d0f30a4caa90b4e5cd9561450ba"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a964a12bbaa7bec51a2cdc5634d24a09c8ae8d9af938f43f2c7a3aba977da3c9"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1efd3ca1a6294fbc13a495f7a550822c09a0b3ec6cdae12ccec40112e6d75ef9"
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Linux_arm64.tar.gz"
    end
  end

  name "tavily"
  desc "Thin CLI for the Tavily search API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/tavily-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tavily"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tavily"]
    end
  end

  # No zap stanza required

end
