# This file was generated by GoReleaser. DO NOT EDIT.
cask "tavily" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Darwin_x86_64.tar.gz"
      sha256 "51a39e6079b2423607d46d92d64b49da4d30b43216b375094c88af57809b415a"
    end
    on_arm do
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Darwin_arm64.tar.gz"
      sha256 "3476e182a1ad2a419ea2fb52ddaab9f5d9beb8517737e30eb57adf534897277a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Linux_x86_64.tar.gz"
      sha256 "efd43ac16abd960afcb564eaa57f8d8e77889c1ec6de1a03c63e94b32074ac25"
    end
    on_arm do
      url "https://github.com/sapihav/tavily-cli/releases/download/v#{version}/tavily-cli_Linux_arm64.tar.gz"
      sha256 "0490da9f961e3daf507972919968f4551562c0021a4159a44495c4c3abb02c7a"
    end
  end

  name "tavily"
  desc "Thin CLI for the Tavily search API — agent-friendly JSON output"
  homepage "https://github.com/sapihav/tavily-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tavily"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tavily"]
    end
  end

  # No zap stanza required

end
