# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CraftCli < Formula
  desc "CLI for interacting with Craft.do documents"
  homepage "https://github.com/sapihav/craft-cli"
  version "1.13.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.13.4/craft-cli_Darwin_x86_64.tar.gz"
      sha256 "3cfcf695e125956a4625237a35ff924d7a3ba03b4ecb8baf311e1dc45c29b7b9"

      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.13.4/craft-cli_Darwin_arm64.tar.gz"
      sha256 "c4fe2cd2cfa81f8fbb60b214db986a2e562684e589eec69511a08838baac4f45"

      define_method(:install) do
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.13.4/craft-cli_Linux_x86_64.tar.gz"
      sha256 "945b21ba66cb28585fa918c259edc111e5a3097ba2d6335fca34adc95db52b00"
      define_method(:install) do
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sapihav/craft-cli/releases/download/v1.13.4/craft-cli_Linux_arm64.tar.gz"
      sha256 "cb70305891643925ac45d4b0a69f4173f833a972955a5ca9cda7649ae3a1a5ca"
      define_method(:install) do
        bin.install "craft"
      end
    end
  end
end
